#!/usr/bin/env python

# Build script for filament's C/C++ extensions.
#
# Package metadata lives in pyproject.toml (PEP 621). This file exists for the
# things declarative metadata cannot express: the C/C++ extension modules and
# three pieces of custom build-time logic --
#
#   1. locating the correct greenlet.h (vendored on Py3, system on Py2),
#   2. materializing the fiber-core config header from FIL_FIBER_CORE, and
#   3. tuning the OPT / debug compiler flags.
#
# On Python 3.9+ setuptools reads ext_modules from here as part of a PEP 517
# build. On Python 2.7 (test-only; no wheels published) pyproject.toml is
# ignored and this file is driven directly with
# `python setup.py build_ext --inplace`, which only needs ext_modules.

import os
import subprocess
import sys

import setuptools
from setuptools import Extension

# Import distutils' sysconfig *after* setuptools so its distutils shim is in
# place on Python 3.12+ (where the stdlib distutils has been removed).
from distutils import sysconfig


def _greenlet_header_exists(hdr_dir):
    return os.path.exists(os.path.join(hdr_dir, 'greenlet.h'))


def _greenlet_include_dir():
    """Find the greenlet include directory.  It may be different than
    the python include directory that the extension builder adds
    automatically.  If it is the same, return None.  Otherwise, return
    the path or raise.

    On Python 3 we use the vendored greenlet (built privately as the
    ``_fil_greenlet`` extension) so filament controls the switch fast
    path; the vendored header must win the include search.  Python 2
    keeps building against the system/venv greenlet -- do not remove
    that path.
    """
    if sys.version_info[0] >= 3:
        vendored = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                'vendor', 'greenlet')
        if _greenlet_header_exists(vendored):
            return vendored

    py_inc = sysconfig.get_python_inc()

    def _get_python_part():
        path_parts = os.path.split(py_inc)
        # if 'py_inc' ends in a /, then the last part of the split is '', so
        # look at the previous one
        python_part = path_parts[-1] if path_parts[-1] else path_parts[-2]
        # We might have something like 'python3.5m', so drop last char while
        # it's not a digit
        while python_part and not python_part[-1].isdigit():
            python_part = python_part[:-1]
        return python_part

    def _search_dir(path):
        for x in range(2):
            if _greenlet_header_exists(path):
                return path
            path = os.path.join(path, 'greenlet')

    python_part = _get_python_part()

    # Check venv first.
    venv = os.environ.get('VIRTUAL_ENV')
    if venv:
        gl_hdr_dir = os.path.join(venv, 'include', 'site',
                                  python_part)
        for x in range(2):
            if _greenlet_header_exists(gl_hdr_dir):
                return gl_hdr_dir
            gl_hdr_dir = os.path.join(gl_hdr_dir, 'greenlet')

    gl_hdr_dir = _search_dir(py_inc)
    if gl_hdr_dir:
        if gl_hdr_dir == py_inc:
            return
        return gl_hdr_dir

    # Next best guess is it's in /usr/local/include/<python>/
    gl_hdr_dir = _search_dir(os.path.join(os.path.sep,
                             'usr',
                             'local',
                             'include',
                             python_part))
    if gl_hdr_dir:
        return gl_hdr_dir
    raise RuntimeError('Not sure where the greenlet header is')


gl_inc = _greenlet_include_dir()
if gl_inc:
    cflags = os.environ.get("CFLAGS")
    cflags = "%s%s-I%s" % (cflags or '', ' ' if cflags else '', gl_inc)
    os.environ['CFLAGS'] = cflags

# Private-stack fiber core for the vendored greenlet.  ON by default;
# configurations the core does not support (see
# vendor/greenlet/greenlet_cpython_compat.hpp for the exact gate)
# silently keep the classic stack-slicing core, so the flag only
# matters where the fiber core is actually eligible.
# Opt out with: FIL_FIBER_CORE=0 python setup.py build_ext --inplace
# (remember to `rm -rf build` when flipping the flag).
#
# The selection is materialized as a tiny generated header rather than a
# -D flag because modern setuptools does not forward the CFLAGS
# environment variable to C++ compiles.  The header is (re)written on
# every setup.py run so a flag flip always takes effect.
def _write_fiber_config():
    enabled = os.environ.get('FIL_FIBER_CORE') != '0'
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        'vendor', 'greenlet', 'fil_fiber_config.h')
    body = (
        "/* Generated by setup.py from the FIL_FIBER_CORE environment\n"
        " * variable; do not edit, do not commit. */\n"
        "%s#define FIL_FIBER_CORE 1\n" % ('' if enabled else '/* classic core */ // ')
    )
    try:
        with open(path) as f:
            current = f.read()
    except (IOError, OSError):
        current = None
    if current != body:
        with open(path, 'w') as f:
            f.write(body)


_write_fiber_config()

if '--debug' in sys.argv:
    orig_opt = sysconfig.get_config_var('OPT')
    opt = '-g'
    if orig_opt:
        for x in orig_opt.split(' '):
            if x.startswith('-W'):
                opt += ' ' + x
    os.environ['OPT'] = opt
else:
    if not os.environ.get('OPT'):
        orig_opt = sysconfig.get_config_var('OPT')
        opt = ''
        if orig_opt:
            got_o = False
            for x in orig_opt.split(' '):
                if x == '-g':
                    continue
                if x.startswith('-O'):
                    got_o = True
                opt += '%s%s' % (' ' if opt else '', x)
            if not got_o:
                opt += '%s-O2' % (' ' if opt else '')
        else:
            opt = '-O2 -DNDEBUG'
        os.environ['OPT'] = opt


# C/C++ extension modules. Translated 1:1 from the pbr-era setup.cfg
# [extension=*] blocks. The greenlet include dir (vendored on Py3) is injected
# globally via CFLAGS above; each extension adds its own local include roots.
def _ext(name, sources, include_dirs=None, libraries=None, language='c',
         library_dirs=None):
    return Extension(
        name,
        sources=sources,
        include_dirs=include_dirs or [],
        libraries=libraries or [],
        library_dirs=library_dirs or [],
        language=language,
    )


def _run(cmd):
    """Run a helper command, returning stripped stdout or None if unusable."""
    try:
        devnull = open(os.devnull, 'w')
        try:
            out = subprocess.check_output(cmd, stderr=devnull)
        finally:
            devnull.close()
    except Exception:
        return None
    out = out.decode('utf-8', 'replace').strip()
    return out or None


def _libevent_dirs():
    """Locate libevent's headers and libraries.

    On Linux the distro package lands in the compiler's default search path and
    this returns empty lists -- nothing to add.  Homebrew on macOS installs
    outside that path (``/opt/homebrew`` on Apple Silicon, ``/usr/local`` on
    Intel), so ``event2/event.h`` is not found without help.

    Resolution order, first hit wins:
      1. ``LIBEVENT_PREFIX`` -- explicit override, for unusual installs.
      2. ``pkg-config libevent`` -- authoritative when present, and correct for
         Homebrew, MacPorts and most Linux distros alike.
      3. ``brew --prefix libevent`` -- Homebrew without pkg-config.
      4. The two standard Homebrew prefixes, probed for the header directly.

    Never raises: if nothing is found we return empty lists and let the
    compiler produce its own (clearer) "file not found" error.
    """
    prefix = os.environ.get('LIBEVENT_PREFIX')
    if prefix:
        return ([os.path.join(prefix, 'include')],
                [os.path.join(prefix, 'lib')])

    inc = _run(['pkg-config', '--cflags-only-I', 'libevent'])
    lib = _run(['pkg-config', '--libs-only-L', 'libevent'])
    if inc or lib:
        # pkg-config emits "-I/a -I/b" / "-L/a"; strip the flag prefixes.
        incs = [p[2:] for p in (inc or '').split() if p.startswith('-I')]
        libs = [p[2:] for p in (lib or '').split() if p.startswith('-L')]
        if incs or libs:
            return incs, libs

    prefix = _run(['brew', '--prefix', 'libevent'])
    if prefix and os.path.exists(os.path.join(prefix, 'include', 'event2',
                                              'event.h')):
        return ([os.path.join(prefix, 'include')],
                [os.path.join(prefix, 'lib')])

    for prefix in ('/opt/homebrew', '/usr/local'):
        if os.path.exists(os.path.join(prefix, 'include', 'event2',
                                       'event.h')):
            return ([os.path.join(prefix, 'include')],
                    [os.path.join(prefix, 'lib')])

    return [], []


_LIBEVENT_INCLUDE, _LIBEVENT_LIB = _libevent_dirs()


ext_modules = [
    # Vendored greenlet 3.5.4 (Python 3 only): private switching core with the
    # filament fast-switch entry.  Python 2 builds keep using the installed
    # greenlet; this extension simply fails cleanly there (prototype note).
    _ext(
        '_fil_greenlet',
        sources=['vendor/greenlet/greenlet.cpp'],
        include_dirs=['./vendor/greenlet'],
        language='c++',
    ),
    _ext(
        '_filament.core',
        sources=[
            'src/core/filament.c',
            'src/core/fil_scheduler.c',
            'src/core/fil_exceptions.c',
            'src/core/fil_message.c',
        ],
        include_dirs=['./include'],
        libraries=['pthread'],
    ),
    _ext(
        '_filament.queue',
        sources=[
            'src/queue/fil_queue_mod.c',
            'src/queue/fil_queue.c',
            'src/queue/fil_simple_queue.c',
        ],
        include_dirs=['./include'],
        libraries=['pthread'],
    ),
    _ext(
        '_filament.locking',
        sources=[
            'src/locking/fil_cond.c',
            'src/locking/fil_lock.c',
            'src/locking/fil_locking.c',
            'src/locking/fil_semaphore.c',
        ],
        include_dirs=['./include'],
        libraries=['pthread'],
    ),
    _ext(
        '_filament.timer',
        sources=['src/timer/fil_timer.c'],
        include_dirs=['./include'],
        libraries=['pthread'],
    ),
    _ext(
        '_filament.io',
        sources=[
            'src/io/fil_io.c',
            'src/io/fil_iothread.c',
        ],
        include_dirs=['./include'] + _LIBEVENT_INCLUDE,
        library_dirs=_LIBEVENT_LIB,
        libraries=['pthread', 'event_pthreads', 'event_core'],
    ),
    _ext(
        '_filament.socket',
        sources=['src/socket/fil_socket.c'],
        include_dirs=['./include'],
        libraries=['pthread'],
    ),
    _ext(
        '_filament.thrpool',
        sources=['src/thrpool/fil_thrpool.c'],
        include_dirs=['./include'],
        libraries=['pthread'],
    ),
]


setuptools.setup(ext_modules=ext_modules)
